spring:
  datasource:
    url: jdbc:mysql://mysql:3306/taskmanager?useSSL=false&allowPublicKeyRetrieval=true
    username: taskuser
    password: ${DATASOURCE_PASSWORD}
    hikari:
      initialization-fail-timeout: 0

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: none

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
